---
title: "draft final Project"
author: "Elise Harrigan and Katie Krejsa"
date: "4/19/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


[knitting](../ENV872_EDA_FinalProject/img/elephant.png)

## ELEPHANT MOVEMENT IN GABON, AFRICA

Elephants are universally some of the most beloved and threatened species in Africa. As a charismatic megafauna, they capture the attention of people as a majestic and powerful animal roaming the African forest and plains. But elephants are also critical in forest ecosystems. As elephant herds travel, they remove trees to create space, consume an incredible amounts of vegetation and use water bodies and dirt piles to cool off. The daily actions of elephants inevitably leave a network of trails in their wake. To be able to better understand forest elephants' daily movements, we will study the trails used by the forest elephant of Gabon. 

Gabon is a country located on the western coast of Africa and covered in dense forest. Due to the forest canopy coverage, collecting data on the elephant trails can be difficult because satellite imagery is not able to penetrate past the top layers of the forest to capture the trail locations on the forest floor. In order to gather more information on elephant movements, data were collected in the field and was analyzed in this study. 


## STUDY QUESTIONS

This study focused on understanding the use of elephant trails and the frequency of travel on these trails. We analyzed the condition of trail as poor, medium or heavy trodden, the width of the trail, and the use denoted by the start, stop or change direction in the trail. We aimed to answer the following questions to gain information on the activity level of elephants and the use of the trails.

1. What is the condition and use of the trail? 
2. What is frequency and number of days traveled on each trail? 


By studying and better understanding the movements and patterns of elephants, future researchers will be able to compare how elephants react to human disturbance, how they impact the vegetation, and their patterns across the landscape. 

## DATASETS

The data used for this project were collected in and around Ivindo National Park, Gabon by a team of Duke University researchers, local field guides, and forest peoples. Two datasets were provided to us by Dr Amelia Meier of Duke University. Data for waypoints and tracklogs were collected in the field with GPS units as the team searched for and walked along forest elephant trails. The data are both spatial, containing geographic coordinates, and temporal, containing date and time components.

The tracklogs dataset includes GPS data where the field teams were walking. Data contained in this dataset includes the site name (Ivindo), date, time, latitude, and longitude, where everything is recorded in decimal degrees WGS84. The dates of the tracklogs range from February 2018 to May 2018. 

The waypoints dataset includes the waypoints taken by field teams when they started walking on an elephant trail or if the elephant trail changed characteristics. The data contained in this dataset includes date, time, latitude, longitude, trail characteristics (cmt), data on where the elephant trails started and stopped and when the field team got on or of a trail (name), and the symbol used in the GPS (sym). More specifically, the "name" field includes "start" or "stop" if the team got on or off a trail, "trstart" or "trstop" if the trail itself started or disappeared, "change" if a characteristic of the trail change, and "jct" if they came to a trail crossing. In the cmt field, there are two sets of information: a letter (P = poor, M = medium, H = heavy) representing how heavily trodden the path is and a number representing the width of the trail in cm. If the cmt section is blank then the details previously recorded remained the same. Data contained in this dataset was also recorded in decimal degrees WGS84 and the dates of data collection also range from February 2018 to May 2018.
 

__Dataset__  | __Variables__| __Range or Unique Values__| __Central Tendancies__
-------------|--------------|---------------------------|------------------------
IV_tracklogs |site          |                           |                                                              -       |date          |2018-02-05 - 2018-05-25    |
     -       |time          |                           |
     -       |latitude      |-0.3429768 - 0.6005945     |mean = 0.07083619; median = -0.1230693
     -       |longitude     |12.43589 - 12.81332        |mean = 12.60479; median = 12.60231
IV_wgts      |date          |2018-02-06 - 2018-05-25    |
     -       |time          |                           |
     -       |latitude      |-0.335521 - 0.599461       |mean = 0.2283088; median = 0.486579
     -       |longitude     |12.43817 - 12.80200        |mean = 12.66357; median = 12.72618
     -       |name          |                           |
     -       |sym           |                           |
     -       |cmt (letter)  | "P" "M" "W"               |
     -       |cmt (number)  | 35 - 75                   |mean = 50; median = 47.5
     

__Data Wrangling__

The overall goal in wrangling our data was to combine the two files so that all the points on the tracklogs are assigned trail characteristics (on trail, off trail, size and use of trails). Doing this would then allow us to quantify the types of trails that elephants use in which contexts.

The tracklogs dataset included a total of 76,098 observations of 6 variables (X, site, date, time, lat, and lon), and the waypoints dataset included a total of 452 observations of 8 variables (X, date, time, lat, lon, name, sym, and cmt). To assign trail characteristics (cmt and name) from the waypoints dataset to the tracklogs dataset, we could not do a simple join because the dates and times did not match up exactly. So instead, we first identified all of the unique dates in the waypoints dataset. We then filtered the tracklogs dataset so that it only included the unique dates found in the waypoints dataset. This reduced the number of tracklog observations to 42,179.

Because there are many observations on each day, we next combined the date and time columns to create a combined date_time column in each of the two datasets and arranged both datasets by ascending order of date_time. As stated earlier, the two datasets do not have exact matching date_time entires, so to assign cmt column values to the tracklogs dataset based on date_time, we transferred cmt values to the tracklogs dataset if the tracklogs date_time was within a window of the date_time column of the waypoints dataset using a for loop. We then filtered out all of the "NA" values of the resulting tracklogs dataset. We were told that if the "cmt" column is blank then the details previously recorded remained the same; Therefore, we filled in blanks with previously recorded values by first filling cells of empty strings with "NA" and then using the fill() command. Because the cmt column holds two pieces of information (a letter representing how heavily trodden the path is and a number representing the width of the trail), we separated these into two separate columns using the str_extract() command. Last, we assigned the "name" column values to the tracklogs dataset in the same way as we assigned the cmt values, using a for loop.

