---
title: "Exploratory_Analysis"
author: "Elise Harrigan"
date: "4/20/2021"
output: html_document
geometry: margin=2.54cm
editor_options:
  chunk_output_type: console
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set up}

getwd()

# Load Packages
library(plyr)
library(stringr)
library(tidyr)
library(lubridate)
library(tidyverse)
library(agricolae) 
library(dplyr)
library(viridis)
library(RColorBrewer)
library(colormap)
library(sf)
library(leaflet)
library(mapview)
library(raster)
library(sp)
library(rgdal)
library(cowplot)
#install.packages("PMCMRplus")
library(PMCMRplus)
#install.packages("rnaturalearth")
#install.packages("rnaturalearthdata")
library(rnaturalearth)

#set theme
mytheme <- theme_light(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "bottom", legend.justification = "right")
theme_set(mytheme)

##load in data - change this to pull from the processed file
tracklogs <- read.csv("./Data/Processed/IV_tracklogs_processed.csv")
wpts <- read.csv("./Data/Processed/IV_wpts_processed.csv")

```

```{r explore the data}
str(tracklogs)
names(tracklogs)
head(tracklogs$lat)
head(tracklogs$lon)
summary(tracklogs)
dim(tracklogs)
#looking for CRS
st_crs(tracklogs)
#none found but Amelia said WGS 84. Googled UTM projection and is in Zone 32S

tracklogs$date <- as.Date(tracklogs$date, format = "%Y-%m-%d")
wpts$date <- as.Date(wpts$date, format = "%Y-%m-%d")

```

```{r}
#subset based on quality of trail
Poor_trails <- tracklogs %>%
  filter(use_cha == "P")

Med_trail <- tracklogs %>% 
  filter(use_cha == "M")

##W not H??
Heavy_trail <- tracklogs %>%
  filter(use_cha == "W")

```

```{r how many P, M, W trails}

P_num <- ggplot(tracklogs, aes(y = use_cha)) +
  geom_bar() + mytheme

print(P_num)

```
__Condition of Trail __      | __Total Amount__
--------------------         |---------------------------
Poor (P)                     | 27,218
Medium (M)                   | 13,666
Heavy (W)                    | 26



```{r}
##plot in ggplots with lat, long

#world is from the rnaturalearth package. gives background for country
world <- ne_countries(scale = "medium", returnclass = "sf")

##ggplot using world map under
Trail_gg <- ggplot(data = world) +
     geom_sf() +
    geom_point(data = tracklogs, aes(x = lon, y = lat, color = use_cha), size = .4)  + 
    coord_sf(xlim=c(12.20, 12.90), ylim=c(-0.5, .8), expand = TRUE) +
  ggtitle("Elephant Trail Points") + 
  xlab("Longitude") + ylab("Latitude") + 
  scale_x_continuous(breaks=seq(12, 13, by = .5)) +
 mytheme
print(Trail_gg)
  

##PLOT IN MAPVIEW for one date

##filter for dates from 04-15-2018
subset_trails <- tracklogs %>%
  filter(date == "2018-04-15")

##subset for each type of trail for 04-15-2018
subset_poor <- Poor_trails %>%
  filter(date == "2018-04-15")

subset_med <- Med_trail %>%
  filter(date == "2018-04-15")

subset_heavy <- Heavy_trail %>%
  filter(date == "2018-04-15")


#CRS=WGS84 4326

#convert to sf and include crs
subset_sf <- st_as_sf(subset_trails, crs = 4326, coords = c("lon", "lat")) 

subset_poor_sf <- st_as_sf(subset_poor, crs = 4326, coords = c("lon", "lat"))
subset_med_sf <- st_as_sf(subset_med, crs = 4326, coords = c("lon", "lat"))
subset_heavy_sf <- st_as_sf(subset_heavy, crs = 4326, coords = c("lon", "lat"))

#Plot the data to see the trails for 2-28-18 
Trail_map1 <- mapview(subset_sf, color = use_cha)
  Trail_map1

#Plot so each type of trail is a different color on 4- 15-18 so heavy is included 
Trail_map2 <- 
mapview(subset_poor_sf, color = "darkseagreen3", col.regions = "darkseagreen4") +
  mapview(subset_med_sf, color = "coral2", col.regions = "coral3") +
    mapview(subset_heavy_sf, color = "lightblue", col.regions = "darkblue")
Trail_map2
```

## ANALYSIS
```{r plots by width}
##Use this plot instead of stacked

width_plots <- ggplot(tracklogs, aes(x = use_cha, y = use_num)) +
  geom_boxplot(fill = "lightblue") + ggtitle("Trail type by width") + xlab("Type of Trail") + ylab("Width of trail (cm)") + mytheme

print(width_plots)

boxplot(use_num ~ use_cha, data = tracklogs)
boxplot(count ~ use_cha, data = tracklogs)

```

```{r boxplots trail by widths}
## NOT USING THESE STACKED PLOTS
##boxplot width of poor trails
PT_plot <- ggplot(Poor_trails, aes(x=use_cha, y=use_num)) +
  geom_boxplot(fill = "seagreen") + 
  ggtitle("Poor Troddened Trail by widths") + 
  xlab("Amount of use") + 
  ylab("Width of trail (cm)") + ylim(35, 55) + mytheme
print(PT_plot)

##boxplot width of medium trails
MT_plot <- ggplot(Med_trail, aes(x=use_cha, y = use_num)) + 
  geom_boxplot(fill = "seagreen3") +
  ggtitle("Medium Troddened Trail by widths") + 
  xlab("Amount of use") + 
  ylab("Width of trail") + mytheme

print(MT_plot)

##boxplot width of heavy trails
HT_plot <- ggplot(Heavy_trail, aes(x=use_cha, y = use_num)) + 
  geom_boxplot(fill = "seagreen4") +
  ggtitle("Heavy Troddened Trail by widths") + 
  xlab("Amount of use") + 
  ylab("Width of trail") + mytheme

print(HT_plot)

##stack the boxplots
tstack<- plot_grid(
  PT_plot,
  MT_plot,
  HT_plot,
align = 'vh', 
hjust = -1, 
ncol = 1)

tstack
```

```{r boxplot # of days}
##boxplot count - number of days a trail was used

freq_plot <- ggplot(tracklogs, aes(x=date, fill = use_cha)) + 
  geom_bar() + 
  scale_fill_manual(values = c("darkseagreen3", "deepskyblue3", "deeppink")) +
  scale_x_date(date_breaks ="10 days", date_labels = "%Y-%m-%d", 
          guide = guide_axis(angle = 45)) + 
  (theme(legend.position = "right", 
        legend.text = element_text(size = 12), legend.title = element_text(size = 12))) +
  labs( y = "Count", 
        x = "Date", 
        title = "Number of Trail Points per Day", 
        fill = "Use of Trail") +
  mytheme

print(freq_plot)

```

```{r model - Analysis}

##which trails have a significantly different width from one another 
mod3 <- lm(data = tracklogs, use_num ~ use_cha)
  summary(mod3)
  TukeyHSD(aov(mod3))
  plot(TukeyHSD(aov(mod3)))
  

  #results W-M, W-P= sig, P-M=not sig




```

